- name: Install docker
  apt:
    name:
      - docker.io
      - docker-compose-plugin
    # state: present
    # update_cache: yes


- name: Down docke-compose
  get_url:
    url: 'http://file.jxm.cool/docker-compose'
    dest: '/usr/local/bin/docker-compose'
    checksum: 'sha256:b49e358d11c198fa228fb7eca2a177affd8e1e33e06d29940668668482f797cd'
    mode: 0755




- name: Download Websocat installed
  get_url:
    # url: 'https://github.com/vi/websocat/releases/download/v1.10.0/websocat.x86_64-unknown-linux-musl'
    url: 'http://file.jxm.cool/websocat'
    dest: '/usr/local/bin/websocat'
    checksum: 'sha256:b3dd771cf71a74e732ff99cf397b4cc62fc000e989d46c4dfbec1b86cc051896'
    mode: 0755
