---
- name: 'Create container dir: {{ nim_waku_cont_name }}'
  file:
    path: '{{ nim_waku_cont_vol }}'
    state: directory
    owner: dockremap
    group: docker

- name: Check if node key file exists
  stat:
    path: '{{ nim_waku_node_key_file_path }}'
  register: key_file

- name: Generate random node key
  throttle: 1
  set_fact:
    # Node key needs to be a 64 char hexadecimal string
    nim_waku_node_key: '{{ lookup("password", "/dev/null") | hash("sha256") }}'
  when: >
    not key_file.stat.exists and
    nim_waku_node_key is not defined
  register: key_generation

- name: Save generate node key to file
  copy:
    dest: '{{ nim_waku_node_key_file_path | mandatory }}'
    content: '{{ nim_waku_node_key | mandatory }}'
    mode: 0400
  when: not key_file.stat.exists

- name: Load existing node key from file
  slurp:
    src: '{{ nim_waku_node_key_file_path | mandatory }}'
  register: key_file
  when: >
    key_generation.skipped is defined and
    nim_waku_node_key is not defined

- name: Extract the node key from file
  set_fact:
    nim_waku_node_key: '{{ key_file.content | b64decode | trim }}'
  when: >
    key_generation.skipped is defined and
    nim_waku_node_key is not defined
